#!/usr/bin/env zsh

# This is needed so tput doesn't complain.
#export TERM=xterm-256color

export DEBIAN_FRONTEND=noninteractive

apt-get install -y apt-utils locales automake htop sudo curl git silversearcher-ag neovim docker.io tmux

# Add Yarn sources (without installing it).
# https://yarnpkg.com/lang/en/docs/install/#debian-stable
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

# Add Crystal sources (without installing it).
# https://crystal-lang.org/reference/installation/on_debian_and_ubuntu.html
curl -sL "https://keybase.io/crystal/pgp_keys.asc" | apt-key add - && echo "deb https://dist.crystal-lang.org/apt crystal main" | tee /etc/apt/sources.list.d/crystal.list

apt-get update

wget -O chruby-0.3.9.tar.gz https://github.com/postmodern/chruby/archive/v0.3.9.tar.gz && tar -xzvf chruby-0.3.9.tar.gz && cd chruby-0.3.9 && make install && cd .. && rm -rf chruby-0.3.9*

# https://github.com/nodesource/distributions
curl -sL https://deb.nodesource.com/setup_15.x | bash - && apt-get install -y nodejs

apt-get install -y tzdata apt-utils && echo "America/New_York" > /etc/timezone && dpkg-reconfigure -f noninteractive tzdata

cd /root && mkdir .ssh && chmod 700 .ssh && git clone https://github.com/jakub-stastny/dotfiles.git .dotfiles.git --bare && git --git-dir=/root/.dotfiles.git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*" && git --git-dir=/root/.dotfiles.git fetch && git --git-dir=/root/.dotfiles.git branch --set-upstream-to=origin/master master && git --git-dir=/root/.dotfiles.git --work-tree=/root checkout && ssh-keyscan github.com >> ~/.ssh/known_hosts && zsh ~/.scripts/hooks/dotfiles.install && git --git-dir=/root/.dotfiles.git remote set-url origin git@github.com:jakub-stastny/dotfiles.git && rm -rf ~/.ssh

# Install Pry.
echo "$(tput setaf 2)~$(tput sgr0) Installing Ruby utilities."
gem install pry #gdrive-cli

# Install expect in order to be able to auto-login.
echo "$(tput setaf 2)~$(tput sgr0) Installing expect for auto-login scripts."
apt-get install -y expect-dev

# Emacs.
echo "$(tput setaf 2)~$(tput sgr0) Installing Emacs."
apt-get install -y emacs-nox

# ZSH is the default shell.
chsh -s $(which zsh)
