name: Verify image

# Controls when the action will run.
on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run in $GITHUB_WORKSPACE
        run: cd $GITHUB_WORKSPACE

      - name: Install ZSH
        run: apt-get install -y zsh

      - name: Download the Docker image
        run: docker pull jakubstastny/dev

      - name: Verify the image
        run: ./bin/verify
